core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("echo/", views.echo, name="echo"),
    path("profile/", views.profile, name="profile"),
]

launchpad/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls')),

]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth import get_user_model
from allauth.account.forms import SignupForm
from unfold import widgets


class UpdateEmailForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ["email"]
        widgets = {"email": forms.EmailInput()}


class UpdateNameForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ["first_name", "last_name"]
        widgets = {"first_name": forms.TextInput(), "last_name": forms.TextInput()}


class CustomSignupForm(SignupForm):
    first_name = forms.CharField(max_length=30, label="First Name")
    last_name = forms.CharField(max_length=30, label="Last Name")

    def save(self, request):
        user = super().save(request)
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.save()
        return user

core/views.py
from allauth.account.forms import ChangePasswordForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views.decorators.http import require_POST

from .forms import UpdateEmailForm, UpdateNameForm


def home(request):
    return render(request, "core/home.html")


@require_POST
def echo(request):
    message = request.POST.get("message", "")
    return HttpResponse(f"Echo: {message}")


@login_required
def profile(request):
    name_form = UpdateNameForm(request.POST or None, instance=request.user)
    email_form = UpdateEmailForm(request.POST or None, instance=request.user)
    password_form = ChangePasswordForm(user=request.user, data=request.POST or None)

    if request.method == "POST":
        if "email" in request.POST and email_form.is_valid():
            email_form.save()
        elif "oldpassword" in request.POST and password_form.is_valid():
            password_form.save()
        elif "first_name" or "last_name" in request.POST and name_form.is_valid():
            name_form.save()
        return redirect("profile")
    return render(
        request,
        "core/profile.html",
        {
            "email_form": email_form,
            "password_form": password_form,
            "name_form": name_form,
        },
    )

templates/core/home.html
<c-layouts.guest>

  <div class="text-center text-on-surface-strong dark:text-on-surface-dark-strong py-12">
    <div class="relative w-64 h-64 mx-auto mb-8">
      <div
        class="absolute inset-0 bg-gradient-to-br from-gray-800 via-indigo-900 to-purple-900 rounded-full opacity-80 blur-xl">
      </div>
      <!-- Stars -->
      <div class="absolute inset-0">
        <div class="w-1 h-1 bg-white rounded-full absolute top-10 left-20 opacity-70"></div>
        <div class="w-1 h-1 bg-white rounded-full absolute top-40 left-60 opacity-70"></div>
        <div class="w-1 h-1 bg-white rounded-full absolute top-60 right-20 opacity-70"></div>
      </div>

      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1" stroke="currentColor"
        class="relative w-full h-full">
        <path stroke-linecap="round" stroke-linejoin="round"
          d="M15.59 14.37a6 6 0 0 1-5.84 7.38v-4.8m5.84-2.58a14.98 14.98 0 0 0 6.16-12.12A14.98 14.98 0 0 0 9.631 8.41m5.96 5.96a14.926 14.926 0 0 1-5.841 2.58m-.119-8.54a6 6 0 0 0-7.381 5.84h4.8m2.581-5.84a14.927 14.927 0 0 0-2.58 5.84m2.699 2.7c-.103.021-.207.041-.311.06a15.09 15.09 0 0 1-2.448-2.448 14.9 14.9 0 0 1 .06-.312m-2.24 2.39a4.493 4.493 0 0 0-1.757 4.306 4.493 4.493 0 0 0 4.306-1.758M16.5 9a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0Z" />
      </svg>
    </div>

    <h1 class="text-5xl md:text-6xl font-bold mb-4">
      Simplify the way you build
    </h1>

    <p class="text-xl md:text-2xl text-gray-300 max-w-2xl mx-auto">
      A modern starter kit that combines Django with Alpine.js, HTMX, and Tailwind CSS to help you ship fast without the
      headache
    </p>
  </div>
  <div class="text-center mt-12 mx-auto px-6 pb-12">
    <p class="text-on-surface dark:text-on-surface-dark text-sm tracking-tight uppercase opacity-60 mb-8">Built with
      modern technologies you
      already know and love:</p>
    <div class="flex flex-wrap justify-center items-center gap-x-12 gap-y-8">
      <!-- Django Logo -->
      <div class="text-on-surface-strong dark:text-on-surface-dark-strong">
        <svg version="1.0" viewBox="0 0 128 128" xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="h-14">
          <path
            d="M59.448 0h20.93v96.88c-10.737 2.04-18.62 2.855-27.181 2.855-25.551-.001-38.87-11.551-38.87-33.705 0-21.338 14.135-35.2 36.015-35.2 3.398 0 5.98.272 9.106 1.087zm0 48.765c-2.446-.815-4.485-1.086-7.067-1.086-10.6 0-16.717 6.523-16.717 17.939 0 11.145 5.845 17.26 16.582 17.26 2.309 0 4.212-.136 7.202-.542z" />
          <path
            d="M113.672 32.321V80.84c0 16.717-1.224 24.735-4.893 31.666-3.398 6.661-7.883 10.873-17.124 15.494l-19.435-9.241c9.242-4.35 13.726-8.153 16.58-14 2.99-5.979 3.943-12.91 3.943-31.122V32.321zM92.742.111h20.93v21.474h-20.93z" />
        </svg>

      </div>
      <!-- Alpine.js Logo -->
      <div>
        <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="h-14" viewBox="0 0 128 128">
          <path fill="#77c1d2" fill-rule="evenodd" d="M98.444 35.562 126 62.997 98.444 90.432 70.889 62.997z"
            clip-rule="evenodd" />
          <path fill="#2d3441" fill-rule="evenodd" d="m29.556 35.562 57.126 56.876H31.571L2 62.997z"
            clip-rule="evenodd" />
        </svg>

      </div>
      <!-- HTMX Logo -->
      <div class="text-on-surface-strong dark:text-on-surface-dark-strong ">
        <span class="font-semibold text-2xl">
          &lt;<b class="text-[#3D72D7]">/</b>&gt; htm<b class="text-[#3D72D7]">x</b>
        </span>
      </div>
      <!-- Tailwind CSS Logo -->
      <div>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128" fill="currentColor" class="h-12">
          <path
            d="M64.004 25.602c-17.067 0-27.73 8.53-32 25.597 6.398-8.531 13.867-11.73 22.398-9.597 4.871 1.214 8.352 4.746 12.207 8.66C72.883 56.629 80.145 64 96.004 64c17.066 0 27.73-8.531 32-25.602-6.399 8.536-13.867 11.735-22.399 9.602-4.87-1.215-8.347-4.746-12.207-8.66-6.27-6.367-13.53-13.738-29.394-13.738zM32.004 64c-17.066 0-27.73 8.531-32 25.602C6.402 81.066 13.87 77.867 22.402 80c4.871 1.215 8.352 4.746 12.207 8.66 6.274 6.367 13.536 13.738 29.395 13.738 17.066 0 27.73-8.53 32-25.597-6.399 8.531-13.867 11.73-22.399 9.597-4.87-1.214-8.347-4.746-12.207-8.66C55.128 71.371 47.868 64 32.004 64zm0 0"
            fill="#38bdf8" />
        </svg>

      </div>
    </div>
  </div>
</c-layouts.guest>

templates/core/profile.html
<c-layouts.guest>
  <div class="max-w-7xl mx-auto  p-6 rounded-lg shadow-md py-12">
    <h2 class="text-2xl font-bold text-on-surface dark:text-on-surface-dark mb-6">Your Profile</h2>

    <c-card>
      <h3 class="text-lg font-semibold text-on-surface-strong dark:text-on-surface-dark-strong mb-2">Update Personal
        Info</h3>
      <form method="post" class="space-y-4">
        {% csrf_token %}
        <div>
          <c-input id="id_first_name" name="first_name" placeholder="Old Data" label="First Name" type="text"
            :errors="name_form.first_name.errors" />
        </div>
        <div>
          <c-input id="id_last_name" name="last_name" placeholder="Old Data" label="Last Name" type="text"
            :errors="name_form.last_name.errors" />
        </div>
        <button type="submit"
          class="whitespace-nowrap rounded-radius bg-secondary border border-secondary px-4 py-2 text-sm font-medium tracking-wide text-on-secondary transition hover:opacity-75 text-center focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-secondary active:opacity-100 active:outline-offset-0 disabled:opacity-75 disabled:cursor-not-allowed dark:bg-secondary-dark dark:border-secondary-dark dark:text-on-secondary-dark dark:focus-visible:outline-secondary-dark">Update
          Name</button>
      </form>
    </c-card>
    <h3 class="text-lg font-semibold text-on-surface dark:text-on-surface-dark mb-2">Update Email</h3>
    <form method="post" class="space-y-4 mb-6">
      {% csrf_token %}
      <div>
        <label for="id_email" class="block text-sm font-medium text-gray-700">Email</label>
        {{ email_form.email }}
      </div>
      {% if email_form.errors %}
      <div class="text-red-500 text-sm">{{ email_form.errors }}</div>
      {% endif %}
      <button type="submit" class="w-full bg-blue-600 text-white p-2 rounded-md hover:bg-blue-700">Update Email</button>
    </form>

    <h3 class="text-lg font-semibold text-on-surface dark:text-on-surface-dark mb-2">Change Password</h3>
    <form method="post" class="space-y-4">
      {% csrf_token %}
      <div>
        <label for="id_oldpassword" class="block text-sm font-medium text-gray-700">Current Password</label>
        <input type="password" name="oldpassword" id="id_oldpassword"
          class="mt-1 w-full p-2 border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500" required>
      </div>
      <div>
        <label for="id_password1" class="block text-sm font-medium text-gray-700">New Password</label>
        <input type="password" name="password1" id="id_password1"
          class="mt-1 w-full p-2 border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500" required>
      </div>
      <div>
        <label for="id_password2" class="block text-sm font-medium text-gray-700">Confirm New Password</label>
        <input type="password" name="password2" id="id_password2"
          class="mt-1 w-full p-2 border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500" required>
      </div>
      {% if password_form.errors %}
      <div class="text-red-500 text-sm">{{ password_form.errors }}</div>
      {% endif %}
      <button type="submit" class="w-full bg-blue-600 text-white p-2 rounded-md hover:bg-blue-700">Change
        Password</button>
    </form>
  </div>
</c-layouts.guest>

templates/cotton/application_logo.html
<div class="flex items-center justify-center space-x-3 w-full">
  <c-icons.rocket class="w-6 h-6" />
  <span>Launchpad</span>
</div>

templates/cotton/card.html
<article
  class="group rounded-radius flex flex-col border border-outline bg-surface-alt p-6 text-on-surface dark:border-outline-dark dark:bg-surface-dark-alt dark:text-on-surface-dark">
  {{ slot }}
</article>

templates/cotton/icons/burger.html
<svg {{ attrs }} fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"
    stroke="currentColor">
    <path d="M4 6h16M4 12h16M4 18h16"></path>
</svg>

templates/cotton/icons/close.html
<svg {{ attrs }} fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
</svg>

templates/cotton/icons/rocket.html
<svg {{ attrs }} xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
    stroke="currentColor">
    <path stroke-linecap="round" stroke-linejoin="round"
        d="M15.59 14.37a6 6 0 0 1-5.84 7.38v-4.8m5.84-2.58a14.98 14.98 0 0 0 6.16-12.12A14.98 14.98 0 0 0 9.631 8.41m5.96 5.96a14.926 14.926 0 0 1-5.841 2.58m-.119-8.54a6 6 0 0 0-7.381 5.84h4.8m2.581-5.84a14.927 14.927 0 0 0-2.58 5.84m2.699 2.7c-.103.021-.207.041-.311.06a15.09 15.09 0 0 1-2.448-2.448 14.9 14.9 0 0 1 .06-.312m-2.24 2.39a4.493 4.493 0 0 0-1.757 4.306 4.493 4.493 0 0 0 4.306-1.758M16.5 9a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0Z" />
</svg>

templates/cotton/input.html
<c-vars type label name id placeholder errors />


{% if type == "password" %}
<div class="flex w-full flex-col gap-1 text-on-surface dark:text-on-surface-dark">
  <label for="{{ id }}" class="w-fit pl-0.5 text-sm">{{ label }}</label>
  <div x-data="{ showPassword: false }" class="relative">
    <input x-bind:type="showPassword ? 'text' : 'password'" id="{{ id }}"
      class="w-full rounded-radius border border-outline bg-surface-alt px-3 py-3 text-sm focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary disabled:cursor-not-allowed disabled:opacity-75 dark:border-outline-dark dark:bg-surface-dark-alt/50 dark:focus-visible:outline-primary-dark"
      id="{{ id }}" name="{{ name }}" placeholder="{{ placeholder }}" {{ attrs }} />
    <button type="button" x-on:click="showPassword = !showPassword"
      class="absolute right-2.5 top-1/2 -translate-y-1/2 text-on-surface dark:text-on-surface-dark"
      aria-label="Show password">
      <svg x-show="!showPassword" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
        stroke="currentColor" aria-hidden="true" class="size-5">
        <path stroke-linecap="round" stroke-linejoin="round"
          d="M2.036 12.322a1.012 1.012 0 0 1 0-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178Z" />
        <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
      </svg>
      <svg x-show="showPassword" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
        stroke="currentColor" aria-hidden="true" class="size-5">
        <path stroke-linecap="round" stroke-linejoin="round"
          d="M3.98 8.223A10.477 10.477 0 0 0 1.934 12C3.226 16.338 7.244 19.5 12 19.5c.993 0 1.953-.138 2.863-.395M6.228 6.228A10.451 10.451 0 0 1 12 4.5c4.756 0 8.773 3.162 10.065 7.498a10.522 10.522 0 0 1-4.293 5.774M6.228 6.228 3 3m3.228 3.228 3.65 3.65m7.894 7.894L21 21m-3.228-3.228-3.65-3.65m0 0a3 3 0 1 0-4.243-4.243m4.242 4.242L9.88 9.88" />
      </svg>
    </button>
  </div>
</div>
{% if errors %}
{% for error in errors %}
<small class="pl-0.5 text-danger">{{ error }}</small>
{% endfor %}
{% endif %}

{% elif type == "text" or "email" %}
<div class="flex w-full flex-col gap-1 text-on-surface dark:text-on-surface-dark">
  <label for="{{ id }}" class="w-fit pl-0.5 text-sm">{{ label }}</label>
  <input id="{{ id }}" type="{{ type }}"
    class="w-full rounded-radius border border-outline bg-surface-alt px-3 py-3 text-sm focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary disabled:cursor-not-allowed disabled:opacity-75 dark:border-outline-dark dark:bg-surface-dark-alt/50 dark:focus-visible:outline-primary-dark"
    name="{{ name }}" placeholder="{{ placeholder }}" {{ attrs }} />
</div>
{% if errors %}
{% for error in errors %}
<small class="pl-0.5 text-danger">{{ error }}</small>
{% endfor %}
{% endif %}
{% endif %}

templates/cotton/layouts/guest.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-screen" data-theme="dark">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="{% static 'css/output.css' %}" />
  <title>Launchpad</title>
</head>

<body class="bg-surface dark:bg-surface-dark text-on-surface dark:text-on-surface-dark min-h-screen flex flex-col">
  <c-navbar />
  {{ slot }}
  <script src="{% static 'js/bundle.js' %}"></script>
</body>

</html>

templates/cotton/navbar.html
<nav x-data="{ mobileMenuIsOpen: false }" x-on:click.away="mobileMenuIsOpen = false"
  class="flex items-center justify-between border-b border-outline px-6 py-4 dark:border-outline-dark"
  aria-label="launchpad menu">
  <!-- Brand Logo -->
  <a href="{% url 'home' %}" class="text-2xl font-bold text-on-surface-strong dark:text-on-surface-dark-strong">
    <c-application-logo />
  </a>
  <!-- Desktop Menu -->
  <ul class="hidden items-center gap-4 md:flex">

    {% if user.is_authenticated %}
    <li><a href="{% url 'profile' %}"
        class="font-medium text-on-surface underline-offset-2 hover:text-primary focus:outline-hidden focus:underline dark:text-on-surface-dark dark:hover:text-primary-dark">Profile</a>
    </li>
    <li><a href="{% url 'account_logout' %}"
        class="font-medium text-on-surface underline-offset-2 hover:text-primary focus:outline-hidden focus:underline dark:text-on-surface-dark dark:hover:text-primary-dark">Logout</a>
    </li>
    {% else %}
    <li><a href="{% url 'account_signup' %}"
        class="font-medium text-on-surface underline-offset-2 hover:text-primary focus:outline-hidden focus:underline dark:text-on-surface-dark dark:hover:text-primary-dark">Signup</a>
    </li>
    <li><a href="{% url 'account_login' %}"
        class="font-medium text-on-surface underline-offset-2 hover:text-primary focus:outline-hidden focus:underline dark:text-on-surface-dark dark:hover:text-primary-dark">Login</a>
    </li>
    {% endif %}
  </ul>
  <!-- Mobile Menu Button -->
  <button x-on:click="mobileMenuIsOpen = !mobileMenuIsOpen" x-bind:aria-expanded="mobileMenuIsOpen"
    x-bind:class="mobileMenuIsOpen ? 'fixed top-6 right-6 z-20' : null" type="button"
    class="flex text-on-surface dark:text-on-surface-dark md:hidden" aria-label="mobile menu"
    aria-controls="mobileMenu">
    <svg x-cloak x-show="!mobileMenuIsOpen" xmlns="http://www.w3.org/2000/svg" fill="none" aria-hidden="true"
      viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="size-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
    </svg>
    <svg x-cloak x-show="mobileMenuIsOpen" xmlns="http://www.w3.org/2000/svg" fill="none" aria-hidden="true"
      viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="size-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
    </svg>
  </button>
  <!-- Mobile Menu -->
  <ul x-cloak x-show="mobileMenuIsOpen"
    x-transition:enter="transition motion-reduce:transition-none ease-out duration-300"
    x-transition:enter-start="-translate-y-full" x-transition:enter-end="translate-y-0"
    x-transition:leave="transition motion-reduce:transition-none ease-out duration-300"
    x-transition:leave-start="translate-y-0" x-transition:leave-end="-translate-y-full" id="mobileMenu"
    class="fixed max-h-svh overflow-y-auto inset-x-0 top-0 z-10 flex flex-col divide-y divide-outline rounded-b-radius border-b border-outline bg-surface-alt px-6 pb-6 pt-20 dark:divide-outline-dark dark:border-outline-dark dark:bg-surface-dark-alt md:hidden">

    {% if user.is_authenticated %}
    <li class="py-4"><a href="{% url 'profile' %}"
        class="w-full text-lg font-medium text-on-surface focus:underline dark:text-on-surface-dark">Profile</a></li>

    <li class="py-4"><a href="{% url 'account_logout' %}"
        class="w-full text-lg font-medium text-on-surface focus:underline dark:text-on-surface-dark">Logout</a></li>
    {% else %}
    <li class="py-4"><a href="{% url 'account_login' %}"
        class="w-full text-lg font-medium text-on-surface focus:underline dark:text-on-surface-dark">Login</a></li>

    <li class="py-4"><a href="{% url 'account_signup' %}"
        class="w-full text-lg font-medium text-on-surface focus:underline dark:text-on-surface-dark">Signup</a></li>
    {% endif %}
  </ul>
</nav>